### ISSUE TITLE
Error grabbing steam api json

### ISSUE THREAD

**Issue by BzowK** [dignifiedweb/OculusHomeIconChanger#3]
Hey!

So... tried using the Icon Changer this morning and upon launch got the message "Error grabbing steam api json."  After clicking OK, I then got an "Unhandled exception..." message - details below...

![error1](https://user-images.githubusercontent.com/4173211/69755926-f5474080-111e-11ea-90cd-a16df8e36456.jpg)
![error2](https://user-images.githubusercontent.com/4173211/69755934-f7a99a80-111e-11ea-8c9b-79294510eb1a.jpg)

I tried the following, but the issue persists:
- Restarting Oculus service
- Restarting Steam
- Restarting PC
- Downloading Release (Alpha 11) again and replacing existing files with ones from its zip

I did notice that Steam updated yesterday, so didn't know if something changed or was related.  Are you seeing the issue?

Anyways, just wanted to post about it.  Hope all's well and happy thanksgiving!!

**Exception Detail**
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at OculusHomeIconChangerNS.OculusHomeIconChanger.GetSteamAppID(String appname)
   at OculusHomeIconChangerNS.OculusHomeIconChanger.radShowOnlySteamApps_CheckedChanged(Object sender, EventArgs e)
   at OculusHomeIconChangerNS.OculusHomeIconChanger.ApplySelectedFilter()
   at OculusHomeIconChangerNS.OculusHomeIconChanger.radSortByDateDesc_CheckedChanged(Object sender, EventArgs e)
   at System.Windows.Forms.RadioButton.OnCheckedChanged(EventArgs e)
   at System.Windows.Forms.RadioButton.set_Checked(Boolean value)
   at System.Windows.Forms.RadioButton.OnClick(EventArgs e)
   at System.Windows.Forms.RadioButton.OnEnter(EventArgs e)
   at System.Windows.Forms.Control.NotifyEnter()
   at System.Windows.Forms.ContainerControl.UpdateFocusedControl()

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4042.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
OculusHomeIconChanger
    Assembly Version: 0.0.11.0
    Win32 Version: 0.0.11.0
    CodeBase: file:///C:/Program%20Files%20(x86)/OculusHomeIconChanger-Alpha11/OculusHomeIconChanger.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4042.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4001.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4042.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 10.0.0.0
    Win32 Version: 10.0.3.21018
    CodeBase: file:///C:/Program%20Files%20(x86)/OculusHomeIconChanger-Alpha11/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3825.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by dignifiedweb** [comment]
Hey, happy Thanksgiving! Sorry you are getting the above error. It has something to do with steams json, I'll have to debug in visual studio. The error means that this url must have changed:
https://api.steampowered.com/ISteamApps/GetAppList/v2/

**Comment by dignifiedweb** [comment]
Are you still getting this error? I am wondering if maybe their API was just down when you were trying? It seems like it's back up. I am not getting the error with my latest release ID. Let me know if you're still getting the error and I'll investigate further. This actually makes me realize I should put this URL (listed above) in the config file in case the steam API changes one day.

**Comment by BzowK** [comment]
Hey - 

Sorry for the late reply - been busy...  Hope you had a good Thanksgiving, too!  Yes, I still get it upon launch.  I've tried:
- Restarting
- Reinstalling .NET 3.5 (Remove then reinstall)
- Reinstalling the app (Extracting files to new path then launching)

Also, I can successfully navigate to that URL in Chrome.  Below's a small snippet of what it yields:
{"applist":{"apps":[{"appid":960770,"name":"Moe Jigsaw - Sengoku†Koihime Pack"},{"appid":960771,"name":"Moe Jigsaw - Unlucky Reverse Pack"},{"appid":960781,"name":"Monster Hunter: World - High Resolution Texture Pack"},{"appid":960790,"name":"DON'T GIVE UP: A Cynical Tale Demo"},{"appid":960800,"name":"Second World: Air War S"},{"appid":960820,"name":"Data mining 2"},{"appid":960831,"name":"HITMAN™ 2 - GOTY Legacy Pack"},{"appid":960890,"name":"Adolescent Santa Claus OST And ART"},{"appid":960900,"name":"Lornsword Winter Chronicle"},{"appid":960920,"name":"Europa Universalis IV: Golden Century "},{"appid":960940,"name":"VRiczat - The Virtual Reality Cricket Game"},{"appid":960980,"name":"Apsulov: End of Gods"},{"appid":961000

Not sure what gives with it...  

More more thing while at it...
I've noticed that the "Recent" sorting of titles in my library is always messed up.  Fir example, I just browsed it and about half of them state I last played them "Just now".   The other half are labeled correctly, though.  Any idea why that is or what I could check to resolve it?  I thought it may be some sort of ID which needs to be unique per title and may need to be changed in my script as I noticed that two titles I launched yesterday (which I couldn't add using my script) appear correctly.  However, I haven't launched anything today so not sure why it states "Just now" for the others so thought I'd ask.

Thanks

**Comment by BzowK** [comment]
Hey -

Hope all's well!  Haven't been able to use OHIC since I made this post, so wanted to update it when trying to use it again today.  Almost positive its not a connectivity / URL issue and seems related to .NET perhaps.  Tried a few things today and belows up to date info.  If you have suggestions or thoughts, please let me know...

**System / Environment**
- Windows 10 1909 x64
- .Oculus / Steam : Latest versions installed
- .NET Version: 4.8 _(Win10 May 2019 Update - full details for versions & updates attached)_
[dotNETVersionDetail.txt](https://github.com/dignifiedweb/OculusHomeIconChanger/files/4175119/dotNETVersionDetail.txt)
- OHIC: Alpha 11

**OHCI Behavior**
1. Launch app
2. Omce main wimdow appears (but splashscreen still shown), I get the error "Error grabbing steam api json"
3. Clicking OK on the error yields the error in the attached Error1.txt
[Error1.txt](https://github.com/dignifiedweb/OculusHomeIconChanger/files/4175121/Error1.txt)
4. If I click Continue, list of apps is shown.  If I select ome and choose "Get Steam Banners", I get another error with detail in Error2.txt.
[Error2.txt](https://github.com/dignifiedweb/OculusHomeIconChanger/files/4175122/Error2.txt)

Only other thing I planned to try next was downgrading .NET to 4.7.x, but as doing so is a pain plus have another app requiring 4.8, wanted to post here first to see what version you were on, if Alpha 11 should support 4.8, or any other thoughts.

Thanks!

**Comment by dignifiedweb** [comment]
Hey, I dont know if you can downgrade .net versions now? Its embedded into windows now. I thought that may be it since I had 1809 still. I upgraded to 1909 like you and I still dont get errors. I'll try to google the errors you received. I think it may be to do with a class i used called newtonsoft json. 

Sorry you're still not able to use app! I'll try to run on different computers and see if I get your errors too.

**Comment by BzowK** [comment]
Hey -

Yeah, remembered that after posting.  Probably should have known being an SCCM PFE :).  Does app require Oculus be installed or only look for the json + image files in their typical paths?  Considered mapping them if works on different PC if no install if needed.

Thanks

**Comment by BzowK** [comment]
**UPDATE**

On a different PC (1909), I created an Oculus folder within Program Files, copied the CoreData folder plus contents into it, and set permissions.  I launched OHIC, but got an error that Oculus files were not in the correct path of C:\Program Files (x86)\Oculus (which is strange since they are not in (x86) on my original box) but moved the Oculus folder there, relaunched, and it worked as designed.

Definitely something on my original PC, but what - I don't know.  I uninstalled Visual Studio since I had installed it around that time and it had added many .NET things, but no change.  Let me know if you find anything out, but don't waste any time on it.

Thanks!

**Comment by dignifiedweb** [comment]
Awesome! Glad it works on 1 pc of yours. But, I want to still look into it more tomorrow. Unfortunately, got too busy tonight, will have a look tomorrow. 

I am wondering if publishing with a later version of .net would fix it for you. I can check tomorrow how easy that would be.

**Comment by dignifiedweb** [comment]
I tried to pinpoint the error that could be causing it. I am really not sure. I will still have to do more research, which I don't know if I'll have time to do much this week. Maybe if I compiled a simpler app with buttons to see what DLL is causing the error for you?

**Comment by BzowK** [comment]
Sounds great - Whenever you have time, I'd appreciate that.  Thanks!

**Comment by dignifiedweb** [comment]
@BzowK , hope you are doing well! It's been a couple years now. I must not have reached out to you about creating the DLL with this use case fix. Sorry about that. Is the issue still happening for you? I am not sure how many people still use this app to be honest. Oculus Home does an *ok* job of grabbing images now it seems too. The steam ones direct are still better I am finding though. There's a new issue that someone else posted here that I'll have to publish to repo.
